README.md
apiExamples/slots.html
demo/apiExamples.md
demo/demo.md
docs/api.md
docs/partials/description.md
package-lock.json
package.json
src/auro-select.js

Changes to be committed:
modified:   apiExamples/slots.html
modified:   demo/apiExamples.md
modified:   demo/demo.md
modified:   docs/api.md
modified:   src/auro-select.js
**Fixes:** #37 
The scope of this update is to correct the slot reference `helptext` and all related docs and demo files.  …

Update helptext reference

---

demo/alertValue.js
demo/apiExamples.md
demo/extractValue.js
docs/api.md
docs/partials/apiExamples.md
src/auro-select.js

**Fixes:** #55
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …

fix(demo): fix js files for extracting value in demo #55

---

apiExamples/presetValue.html
demo/apiExamples.md
docs/partials/apiExamples.md
package-lock.json
src/auro-select.js

**Fixes:** #60 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …

fix(preset): refactor value preset #60

---

src/auro-select.js

**Fixes:** #67
Changes the broken logic for when menu.selectByValue was called. The old method resulted in it being called more often than expected and not in all cases it should have been.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to …

fix(API): change logic for when to run menu.selectByValue #67

---

demo/apiExamples.md
docs/api.md
package-lock.json
package.json
src/auro-select.js
test/auro-select.test.js
web-test-runner.config.mjs

**Fixes:** #38, #75
Adds the ready check behavior for peer dependencies and all automated testing to pass threshold requirements.
-- …

feat(API): add ready state checks and all automated tests #38 #75

---

README.md
apiExamples/valueExtraction.html
demo/alertValue.js
demo/api.html
demo/apiExamples.md
demo/examples.js
demo/extractValue.js
demo/index.html
docs/partials/apiExamples.md
package-lock.json
src/auro-select.js

**Fixes:** #91
Update to new method of executing example.js code previously created in dropdown POC

fix(examples): better handling of JS examples #91

---

package-lock.json
package.json
src/auro-select.js

**Fixes:** #93
Use updated dropdown API

fix(dropdown): use updated dropdown API

---

package-lock.json
src/auro-select.js

**Fixes:** #95
this.value = this.menu.optionSelected.value was not being called when menu made a selection (e.g. clicking on a menu option)
**Thank you for your …

fix(value): correct value stored when selecting from menu #95

---

apiExamples/withSubmenus.html
demo/demo.md
docs/partials/demo.md
package-lock.json
package.json
src/auro-select.js

**Fixes:** #86 
* Added dropdown's new matchWidth attribute in the HTML template
* Added an example of select using nested menus
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …

Support dropdown's matchWidth attribute

---

apiExamples/noCheckmark.html
demo/apiExamples.md
demo/demo.md
docs/api.md
docs/partials/demo.md
src/auro-select.js
test/auro-select.test.js

**Fixes:** #88 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …

add nocheckmark attribute

---

demo/demo.md
docs/partials/demo.md

**Fixes:** #106 
Add demo example descriptions for:
* Example with auro-icons
* Example with nested menus
* Example with no checkmark
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …

docs(examples): add necessary descriptions for demo examples

---

src/auro-select.js

**Fixes:** #109 
Changed screenreader text to easily distinguish active and selected option.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …

Distinguish screenreader text

---

src/style.scss

**Fixes:** #102 
Set background color `auro-color-ui-bkg-hover-on-light`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers …

add hover background color change

---

package-lock.json
src/style.scss

**Fixes:** #81, #112 
Set the height of the dropdown inside of auro-select to use the new `var(--auro-size-500)` design token or a value of 40px when the variable is not defined.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of …

Set select element height

---

src/auro-select.js

**Fixes:** #119 
Applied styles to visually hide the manually created label for screenreaders.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …

Manually hide label created for screenreaders

---

apiExamples/error.html
apiExamples/error.js
demo/api.js
demo/api.md
demo/apiExamples.md
index/demo.md
src/auro-select.js
test/auro-select.test.js

**Fixes:** #137 
Correctly handle `validity` attribute when the `error` attribute is removed.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …

Improve validity handling for adding/removing of the error attribute

---

README.md
demo/index.html
package-lock.json
src/auro-select.js

**Resolves:** # (issue, if applicable)
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require …

perf: alaskaairux ref updates

---

.npmignore

**Resolves:** #174
Update npmignore to latest stadard

fix(npm): update ignore to include src dir #174

---

apiExamples/custom.html
demo/index.md
docs/partials/index.md

Add missing custom registration example to index doc

perf(docs): add custom registration example

---

package.json

Correct the `build:release` script

build(script): correct the build:release script

---

package-lock.json
package.json

Update component to use latest version of auro-menu.

perf(deps): update component to use latest version of menu

---

package-lock.json
package.json

fix: update the dropdown package to fix safari outline bug #131
